name: Create Multi-Arch Manifest
on:
  workflow_dispatch:  # Only triggered manually
jobs:
  create-manifest:
    runs-on: ubuntu-latest
    needs: []  # No dependencies - can run independently
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Calculate version
        id: version
        run: |
          # Get the latest git tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # Get current commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Commit hash: $COMMIT_HASH"
          
          # Create version string
          VERSION="${LATEST_TAG}-${COMMIT_HASH}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create and push multi-arch manifest
        run: |
          # Create manifest for latest
          docker manifest create ghcr.io/agessaman/meshinfo-lite:latest \
            ghcr.io/agessaman/meshinfo-lite:latest-amd64 \
            ghcr.io/agessaman/meshinfo-lite:latest-arm64
          
          # Create manifest for version
          docker manifest create ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.version }} \
            ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.version }}-amd64 \
            ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.version }}-arm64
          
          # Create manifest for tag
          docker manifest create ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.latest_tag }} \
            ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.latest_tag }}-amd64 \
            ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.latest_tag }}-arm64
          
          # Push manifests
          docker manifest push ghcr.io/agessaman/meshinfo-lite:latest
          docker manifest push ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.version }}
          docker manifest push ghcr.io/agessaman/meshinfo-lite:${{ steps.version.outputs.latest_tag }}
